service: overtime-api

useDotenv: true

frameworkVersion: "3"

plugins:
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs18.x
  environment: 
    DATABASE_URL: ${env:DATABASE_URL}
    DB_HOST: ${env:DB_HOST}
    PORT: ${env:PORT}
  region: ap-northeast-1

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
